Make almost all third-party binaries for arm64 and x86_64
Exception: OpenVPN 2.3.18 with OpenSSL 1.0 because OpenSSL 1.0 doesn't build with arm64. (OpenVPN 2.3.18 with LibreSSL is built for both arm64 and x86-64.